apiVersion: siab.io/v1alpha1
kind: SIABApplication
metadata:
  name: redis
  namespace: default
spec:
  image: redis:7.2-alpine
  replicas: 1
  port: 6379

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  security:
    scanOnDeploy: true
    blockCriticalVulns: true

  storage:
    enabled: true
    size: "10Gi"
    mountPath: "/data"

  healthCheck:
    enabled: true
    port: 6379
    initialDelaySeconds: 10
