apiVersion: siab.io/v1alpha1
kind: SIABApplication
metadata:
  name: vscode-server
  namespace: default
spec:
  image: codercom/code-server:4.19.1
  replicas: 1
  port: 8080

  env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: vscode-secret
          key: password

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  security:
    scanOnDeploy: true
    blockCriticalVulns: true

  storage:
    enabled: true
    size: "20Gi"
    mountPath: "/home/coder"

  ingress:
    enabled: true
    hostname: code.siab.local
    tls: true

  auth:
    enabled: true
    requiredRoles:
      - developer
---
apiVersion: v1
kind: Secret
metadata:
  name: vscode-secret
  namespace: default
type: Opaque
stringData:
  password: "dev123"  # Change in production!
