apiVersion: siab.io/v1alpha1
kind: SIABApplication
metadata:
  name: vault
  namespace: default
spec:
  image: hashicorp/vault:1.15
  replicas: 1
  port: 8200

  env:
    - name: VAULT_DEV_ROOT_TOKEN_ID
      value: "root"  # Dev mode only!
    - name: VAULT_ADDR
      value: "http://0.0.0.0:8200"

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  security:
    scanOnDeploy: true
    blockCriticalVulns: true

  storage:
    enabled: true
    size: "10Gi"
    mountPath: "/vault/data"

  ingress:
    enabled: true
    hostname: vault.siab.local
    tls: true

  auth:
    enabled: true
    requiredRoles:
      - admin
      - security-admin
