apiVersion: siab.io/v1alpha1
kind: SIABApplication
metadata:
  name: nginx
  namespace: default
spec:
  image: nginx:1.25-alpine
  replicas: 3
  port: 80

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

  security:
    scanOnDeploy: true
    blockCriticalVulns: true

  ingress:
    enabled: true
    hostname: web.siab.local
    tls: true
    rateLimit:
      enabled: true
      requestsPerSecond: 100
      burstSize: 200

  scaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilization: 70
