apiVersion: siab.io/v1alpha1
kind: SIABApplication
metadata:
  name: gitlab-runner
  namespace: default
spec:
  image: gitlab/gitlab-runner:alpine-v16.6.0
  replicas: 2
  port: 9252  # metrics port

  env:
    - name: RUNNER_EXECUTOR
      value: "kubernetes"
    - name: KUBERNETES_NAMESPACE
      value: "default"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1"
      memory: "512Mi"

  security:
    scanOnDeploy: true
    blockCriticalVulns: true

  scaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilization: 70
